language: cpp
compiler: gcc
dist: xenial

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo add-apt-repository -y ppa:beineri/opt-qt-5.11.2-xenial;
  - sudo apt-get update -qq;

install:
  # C++17
  - sudo apt-get install -qq g++-6;
  - sudo apt-get install qtbase5-dev libqt5widgets5;
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90;
script:
  - cmake .
  - make
  # - ./sample
